[package]
name = "svc-events"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/foxford/svc-events"
description = "Foxford events"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svc-agent = "0.20"
thiserror = "1.0"
